name: build-kernel 
on: [push]
jobs:
  build-kernel:
    runs-on:
      labels: ubuntu-22.04-16core
    steps:
      - uses: actions/checkout@v4
      - run: make defconfig
      - run: make -j $(nproc)
      - run: echo done
